#include "sys/alt_irq.h"

#include "altera_avalon_pio_regs.h"
#include "altera_avalon_timer_regs.h"

#include "system.h"

static unsigned leds = 0;
static unsigned int display1 = 0;
static unsigned int display2 = 0;
static unsigned int display3 = 0;
static unsigned int display4 = 0;
static unsigned int display5 = 0;
static unsigned int display6 = 0;

// Mapeo para los displays
static void displaymap(){

	if (display1 == 0) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 64);
	if (display1 == 1) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 121);
	if (display1 == 2) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 36);
	if (display1 == 3) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 48);
	if (display1 == 4) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 25);
	if (display1 == 5) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 18);
	if (display1 == 6) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 2);
	if (display1 == 7) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 120);
	if (display1 == 8) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 0);
	if (display1 == 9) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 16);
	if (display1 == 10) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 8);
	if (display1 == 11) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 3);
	if (display1 == 12) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 70);
	if (display1 == 13) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 33);
	if (display1 == 14) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 6);
	if (display1 == 15) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 14);
	if (display1 == 16) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY1_0_BASE, 127);

	if (display2 == 0) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 64);
	if (display2 == 1) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 121);
	if (display2 == 2) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 36);
	if (display2 == 3) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 48);
	if (display2 == 4) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 25);
	if (display2 == 5) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 18);
	if (display2 == 6) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 2);
	if (display2 == 7) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 120);
	if (display2 == 8) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 0);
	if (display2 == 9) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 16);
	if (display2 == 10) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 8);
	if (display2 == 11) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 3);
	if (display2 == 12) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 70);
	if (display2 == 13) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 33);
	if (display2 == 14) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 6);
	if (display2 == 15) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 14);
	if (display2 == 16) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY2_0_BASE, 127);

	if (display3 == 0) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 64);
	if (display3 == 1) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 121);
	if (display3 == 2) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 36);
	if (display3 == 3) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 48);
	if (display3 == 4) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 25);
	if (display3 == 5) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 18);
	if (display3 == 6) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 2);
	if (display3 == 7) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 120);
	if (display3 == 8) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 0);
	if (display3 == 9) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 16);
	if (display3 == 10) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 8);
	if (display3 == 11) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 3);
	if (display3 == 12) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 70);
	if (display3 == 13) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 33);
	if (display3 == 14) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 6);
	if (display3 == 15) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 14);
	if (display3 == 16) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY3_0_BASE, 127);

	if (display4 == 0) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 64);
	if (display4 == 1) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 121);
	if (display4 == 2) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 36);
	if (display4 == 3) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 48);
	if (display4 == 4) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 25);
	if (display4 == 5) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 18);
	if (display4 == 6) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 2);
	if (display4 == 7) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 120);
	if (display4 == 8) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 0);
	if (display4 == 9) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 16);
	if (display4 == 10) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 8);
	if (display4 == 11) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 3);
	if (display4 == 12) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 70);
	if (display4 == 13) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 33);
	if (display4 == 14) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 6);
	if (display4 == 15) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 14);
	if (display4 == 16) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY4_0_BASE, 127);

	if (display5 == 0) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 64);
	if (display5 == 1) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 121);
	if (display5 == 2) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 36);
	if (display5 == 3) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 48);
	if (display5 == 4) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 25);
	if (display5 == 5) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 18);
	if (display5 == 6) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 2);
	if (display5 == 7) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 120);
	if (display5 == 8) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 0);
	if (display5 == 9) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 16);
	if (display5 == 10) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 8);
	if (display5 == 11) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 3);
	if (display5 == 12) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 70);
	if (display5 == 13) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 33);
	if (display5 == 14) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 6);
	if (display5 == 15) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 14);
	if (display5 == 16) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY5_0_BASE, 127);

	if (display6 == 0) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 64);
	if (display6 == 1) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 121);
	if (display6 == 2) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 36);
	if (display6 == 3) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 48);
	if (display6 == 4) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 25);
	if (display6 == 5) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 18);
	if (display6 == 6) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 2);
	if (display6 == 7) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 120);
	if (display6 == 8) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 0);
	if (display6 == 9) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 16);
	if (display6 == 10) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 8);
	if (display6 == 11) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 3);
	if (display6 == 12) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 70);
	if (display6 == 13) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 33);
	if (display6 == 14) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 6);
	if (display6 == 15) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 14);
	if (display6 == 16) IOWR_ALTERA_AVALON_PIO_DATA(PIO_DISPLAY6_0_BASE, 127);

}

static void verify_leds(){

	if(display1 == 16){
		display1 = 0;
	}

	if(display2 == 16){
		display2 = 0;
	}

	if(display3 == 16){
		display3 = 0;
	}

	if(display4 == 16){
		display4 = 0;
	}

	if(display5 == 16){
		display5 = 0;
	}

	if(display6 == 16){
		display6 = 0;
	}
}

void static plus_leds(){
	display1++;
	display2 = display1+1;
	display3 = display2+1;
	display4 = display3+1;
	display5 = display4+1;
	display6 = display5+1;

}

static void timer_isr(void *context)
{
	// No usamos esto
	(void) context;

	leds = leds << 1 | (IORD_ALTERA_AVALON_PIO_DATA(PIO_CONTINUE_0_BASE) & 1);
	IOWR_ALTERA_AVALON_PIO_DATA(PIO_LEDS_0_BASE, leds);

	displaymap();
	plus_leds();
	verify_leds();


	// Limpiamos status.TO
	IOWR_ALTERA_AVALON_TIMER_STATUS(TIMER_0_BASE, 0);
}

int main()
{
	// Asociamos la señal de IRQ con el ISR
	alt_ic_isr_register(
			TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID,
			TIMER_0_IRQ,
			timer_isr,
			NULL,
			NULL);

	// Habilitamos IRQs periódicas generadas por el timer
	IOWR_ALTERA_AVALON_TIMER_CONTROL(
			TIMER_0_BASE,
			  ALTERA_AVALON_TIMER_CONTROL_ITO_MSK
			| ALTERA_AVALON_TIMER_CONTROL_CONT_MSK);

	while (1);
}
